### ISSUE TITLE
Не поворачивается пушка

### ISSUE THREAD

**Issue by Taally** [mmcs-gd/aurora2020#24]
https://github.com/Taally/aurora2020/blob/50ad31c36c430008480aead42a3a38b0ae1a24bb/src/characters/player_with_gun.js#L41
@Wolwer1nE

**Comment by Taally** [comment]
UPD: пушка не крутится из-за того, что камера следует за игроком, видимо, где-то надо пересчитывать координаты. В левом верхнем углу карты поворачивается как надо.

**Comment by Wolwer1nE** [comment]
Готово, https://github.com/Taally/aurora2020/pull/1
@Taally Татьяна, вы правы, надо было перенести координаты с учетом положения камеры. Или можно было использовать `pointer.angle`, но тогда больше исправлений надо было делать.

**Comment by Wolwer1nE** [comment]
И добавил анимации WalkWithGun и RunWithGun
